# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('creator', models.CharField(max_length=35)),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lName', models.CharField(max_length=50)),
                ('lType', models.IntegerField(blank=True, choices=[(0, 'restaurant'), (1, 'museum'), (2, 'hotel'), (3, 'cafe'), (4, 'leisure')], default=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib.Dest')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'site_alert'), (1, 'trip_add'), (2, 'new_friend'), (3, 'new_comment')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('creator', models.CharField(max_length=35)),
                ('dests', models.ManyToManyField(to='ib.Dest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40, unique=True)),
                ('fName', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(to='ib.User'),
        ),
        migrations.AddField(
            model_name='note',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib.Trip'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ib.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib.Event'),
        ),
    ]
